<?php
/**
 * @copyright © 2019 by GLV
 * @project Cred GLV Plugin
 *
 * @since 1.0
 *
 */



namespace credglv\core\components;


use credglv\core\BaseObject;
use credglv\core\interfaces\ComponentInterface;

class Cookie extends BaseObject implements ComponentInterface
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
       /* $userId = $this->credglv_user_id;
        if (!$userId) {
            if (is_user_logged_in()) {
                $userId = get_current_user_id();
            } else {
                $userId =
            }
        }*/
    }

    /**
     * @param string $name
     * @return bool
     */
    public function __get($name)
    {
        if (isset($_COOKIE[$name])) {
            return urldecode($_COOKIE[$name]);
        }
        return false;
    }

    /**
     * @param $name
     * @param $value
     * @param int $exp
     */
    public function set($name, $value, $exp = 86400)
    {
        setcookie($name, $value, time() + $exp, '/');
    }
}