<?php
/**
 * @project  cred
 * @copyright © 2019 by thomas
 * @author thomas
 */


namespace credglv\core\components;


use credglv\core\BaseObject;
use credglv\core\interfaces\ComponentInterface;

class Session extends BaseObject implements ComponentInterface
{
    /**
     * Init
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        /**
         * Start session at begin of WP
         */
        if (!session_id() && !headers_sent()) {
            session_start();
        }

    }

    /**
     * @param string $name
     * @param mixed $value
     */
    public function __set($name, $value)
    {
        $_SESSION[$name] = $value;
    }

    /**
     * @param string $name
     * @return mixed
     */
    public function __get($name)
    {
        if (isset($_SESSION[$name])) {
            return $_SESSION[$name];
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }


}